[package]
name = "omics-tools"
version = "0.1.0"
authors = ["YJC <yjcyxky@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
bam = "0.1.1"
rust-htslib = "0.32.0"